Module5 task1
htmlacademy-ecmascript/274941-cinemaddict-16 pull request #8
Opened 2021-12-16 18:27 UTC by teclevel

2021-12-19 01:00 UTC, Ldes reviewed
В целом:

Код файлов `src/generator-data.js` и `src/filter.js` есть смысл перенести в папку `mocks`, и назвать соответствующим образом, исходя из того, за генерацию чего он сейчас отвеча

Файл `src/utils/utils.js` в большей степени сейчас содержит обобщённую логику…
Такие файлы обычно называют common
При этом, в файле есть логика, явно специфичная, для решения конкрретных задач. Сортировка например..
Специфичное было бы круто отделать, чтоб проще было понять, что к чему)

В процессе диалога думаю ещё что-то увидим вместе.. Напиши в тг, когда удобно созвониться)

2021-12-19 01:48 UTC, Ldes commented on src/presenter/film-presenter.js
> +    document.addEventListener('keydown', this.#escKeyDownHandler);
Если так подумать, то нам обработчик на ESC мы в любом случае снимаем, при закрытии попапа.
Например можно воспользоваться опцией once
> once: Boolean указывает, что обработчик должен быть вызван не более одного раза после добавления. Если true, обработчик автоматически удаляется при вызове.

2021-12-19 01:48 UTC, Ldes commented on src/presenter/film-presenter.js
> +  }
Своё решение)
Не удалось или по другой причине?

2021-12-19 01:48 UTC, Ldes commented on src/view/films-list-no-cards-view.js
> +}
Надо пообщаться

2021-12-19 01:48 UTC, Ldes commented on src/view/smart-view.js
> +}
Не совсем понял) Обсудим

2021-12-19 01:48 UTC, Ldes commented on src/view/sort-view.js
> +      <li><a href="#" class="sort__button" data-sort-type="${SortType.RATING}">Sort by rating</a></li>
Классы активности не плохо было бы реализовать на шаблоной логике

2021-12-19 13:08 UTC, teclevel commented on src/view/smart-view.js
> +}
это к следующему заданию

2021-12-19 17:16 UTC, teclevel commented on src/utils/utils.js
> +// };
закомментированные участки убрал, кроме того где не разобрался с повторным открытием попапа другой карточки

2021-12-19 17:21 UTC, teclevel commented on src/view/sort-view.js
> +    // sortType откуда берётся?
здесь понял

2021-12-19 17:21 UTC, teclevel commented on src/presenter/films-list-presenter.js
> +        this.#boardCards.sort((a, b) => a.rating - b.rating);
поправил

2021-12-19 17:22 UTC, teclevel commented on src/main.js
>  import { generateFilter } from './filter';
перенес

2021-12-19 17:24 UTC, teclevel commented on src/utils/utils.js
> +dayjs.extend(RelativeTime);
использовал

2021-12-19 17:24 UTC, teclevel commented on src/presenter/film-presenter.js
> +    document.addEventListener('keydown', this.#escKeyDownHandler);
использовал once

2021-12-21 17:50 UTC, teclevel commented on src/presenter/film-presenter.js
> +  }
не получается, пытался как в лекции с режимами

2021-12-25 14:33 UTC, syutkinadasha requested changes

2021-12-25 14:33 UTC, syutkinadasha commented on src/const.js
> +};
Предлагаю поработать с константой RenderPosition и переименовать в соответствии с критерием Б5 для лучшей читабельности

2021-12-25 14:33 UTC, syutkinadasha commented on src/main.js
> +import { generateFilter } from './mock/filter';
generateFilter надо переименовать, т.к. сейчас название такое, будто это какой-то общий метод для всего, предлагаю generateFilmsFilter - так сразу станет понятно, к чему относится

2021-12-25 14:33 UTC, syutkinadasha commented on src/presenter/film-presenter.js
> +      render(this.#filmsListContainer, this.#filmsCardComponent, RenderPosition.BEFOREEND);
prevCardComponent === null || prevPopupComponent === null так конечно можно делать, но лучше использовать оператор отрицания !. Получится так !prevCardComponent || !prevPopupComponent

2021-12-25 14:33 UTC, syutkinadasha commented on src/presenter/film-presenter.js
> +      evt.preventDefault();
evt.preventDefault(); эта строка не нужна, можно удалить

2021-12-25 14:33 UTC, syutkinadasha commented on src/view/sort-view.js
> +
'sort__button--active' вынеси в константу лучше, чтобы в функции createSortTemplate использовать

2021-12-25 21:00 UTC, merged